### ISSUE TITLE
Has anyone succeeded in DAGM2007 dataset？

### ISSUE THREAD

**Issue by 18813223994** [A03ki/f-AnoGAN#12]
I implement this model in DAGM2007 but got a bad result. Defects cannot be segmented. Am I doing something wrong?
![000010](https://user-images.githubusercontent.com/65879792/167413692-643350fd-6b29-4505-9a68-c8db1d9944a3.png)

**Comment by A03ki** [comment]
Hi, @18813223994. Thank you for using this repository.
This image looks selecting a small epoch number. Could you try to select big epoch number.

Example:
```bash
$ python train_wgangp.py "DAGM2007/Class6/train" --seed 1 --n_epochs 1000 --channels 3 --lr 0.0001
$ python train_encoder_izif.py "DAGM2007/Class6/train" --seed 1 --n_epochs 200  --channels 1 --lr 0.0001
$ python test_anomaly_detection.py "DAGM2007/Class6/test" --channels 3
$ python save_compared_images.py "DAGM2007/Class6/test" --n_grid_lines 10  --channels 3
```
![000650](https://user-images.githubusercontent.com/44111084/172166904-e3c54107-8c39-4155-bf4f-6ebef2096b1e.png)

We can check no scratches on the reconstructed images.
However, this abnormal detection score isn't high.

![ROC-AUC](https://user-images.githubusercontent.com/44111084/172167651-d3087176-f495-4204-9d9f-7113b92c2f1d.png)
![PR-AUC](https://user-images.githubusercontent.com/44111084/172167666-826647a6-a81a-48e1-ab30-6a8807d9649b.png)
![scores](https://user-images.githubusercontent.com/44111084/172167676-b2ba7d84-235e-4cc9-8cab-a5afdb9620bb.png)

The existing model seems weak for tasks such as a carpet from my experience.

<hr>

Training GAN and Encoder setting grayscale maybe give you a little more score because images in DAGM2007 are gray color.

Example:
```bash
$ python train_wgangp.py "DAGM2007/Class6/train" --seed 1 --n_epochs 1000 --channels 1 --lr 0.0001
$ python train_encoder_izif.py "DAGM2007/Class6/train" --seed 1 --n_epochs 200  --channels 1 --lr 0.0001
$ python test_anomaly_detection.py "DAGM2007/Class6/test" --channels 1
$ python save_compared_images.py "DAGM2007/Class6/test" --n_grid_lines 10  --channels 1
```

Before run the above, you should rewritten as follows in [your_own_dataset/train_wgangp.py](https://github.com/A03ki/f-AnoGAN/blob/729bd001c1571492bbd8e5fe30e3cc47d43d1a55/your_own_dataset/train_wgangp.py#L17-L21) and [your_own_dataset/train_encoder_izif.py](https://github.com/A03ki/f-AnoGAN/blob/729bd001c1571492bbd8e5fe30e3cc47d43d1a55/your_own_dataset/train_encoder_izif.py#L17-L21):
```python
transform = transforms.Compose([transforms.Resize([opt.img_size]*2),
                                                  transforms.RandomHorizontalFlip(),
                                                  transforms.RandomVerticalFlip(),
                                                  transforms.Grayscale(num_output_channels=1),
                                                  transforms.ToTensor(),
                                                  transforms.Normalize([0.5], [0.5])])
```
Moreover, rewritten in [your_own_dataset/test_anomaly_detection.py](https://github.com/A03ki/f-AnoGAN/blob/729bd001c1571492bbd8e5fe30e3cc47d43d1a55/your_own_dataset/test_anomaly_detection.py#L15-L19) and [your_own_dataset/save_compared_images.py](https://github.com/A03ki/f-AnoGAN/blob/729bd001c1571492bbd8e5fe30e3cc47d43d1a55/your_own_dataset/save_compared_images.py#L15-L19):
```python
transform = transforms.Compose([transforms.Resize([opt.img_size]*2),
                                                  transforms.Grayscale(num_output_channels=1),
                                                  transforms.ToTensor(),
                                                  transforms.Normalize([0.5], [0.5])])
```
![000650](https://user-images.githubusercontent.com/44111084/172171271-a8a00f9a-557c-4785-a71a-54ec382a73e2.png)
![ROC-AUC](https://user-images.githubusercontent.com/44111084/172171321-4fea2ad3-3f0d-4d16-a94a-00ed6de0da68.png)
![PR-AUC](https://user-images.githubusercontent.com/44111084/172171337-f8dd620b-ca4a-4f83-b279-4b563ddfbd00.png)
![scores](https://user-images.githubusercontent.com/44111084/172171377-4ce45c50-3a63-4481-853b-395fd6fb06c0.png)


<hr>
DL the Class6 dataset and split data.

```bash
$ wget https://conferences.mpi-inf.mpg.de/dagm/2007/Class6.zip
$ wget https://conferences.mpi-inf.mpg.de/dagm/2007/Class6_def.zip
$ mkdir -p DAGM2007/Class6
$ unzip -d DAGM2007/Class6/train Class6.zip
$ unzip -d DAGM2007/Class6/test Class6_def.zip
```

```python
import glob
import shutil
import os

output_dir = "DAGM2007/Class6/test/Class6/"
os.makedirs(output_dir, exist_ok=True)

path = "DAGM2007/Class6/train/Class6/*"
file_paths = sorted(glob.glob(path))

for file_path in file_paths[len(file_paths)//2:]:
    new_path = shutil.move(file_path, output_dir)
```
